services:
  - type: web
    name: telegram-webhook-bot
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python webhook_server.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GROUP_CHAT_ID
        sync: false
      - key: ADMINS
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
